spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  jwt:
    secret: please-change-this-to-a-strong-256-bit-secret
    issuer: jwt-java-mastery
    exp-minutes: 120


logging:
  level:
    org.springframework.security: DEBUG